[context.production.environment]
  SURVICATE_DQS_SURVEY_ID = "c52aa7ca680247d5"
  SURVICATE_DQS_SURVEY_STAR_RATING_QUESTION_ID = "1476089"

[context.deploy-preview.environment]
  SURVICATE_DQS_SURVEY_ID = "4ef30791a4b4838a"
  SURVICATE_DQS_SURVEY_STAR_RATING_QUESTION_ID = "1459131"